package com.wad.model;
// Generated 11/06/2018 11:40:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diagrama generated by hbm2java
 */
public class Diagrama  implements java.io.Serializable {


     private int idDiagrama;
     private String clave;
     private String pregunta;
     private Set<Imagen> imagens = new HashSet<Imagen>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Diagrama() {
    }

	
    public Diagrama(int idDiagrama) {
        this.idDiagrama = idDiagrama;
    }
    public Diagrama(int idDiagrama, String clave, String pregunta, Set<Imagen> imagens, Set<Usuario> usuarios) {
       this.idDiagrama = idDiagrama;
       this.clave = clave;
       this.pregunta = pregunta;
       this.imagens = imagens;
       this.usuarios = usuarios;
    }
   
    public int getIdDiagrama() {
        return this.idDiagrama;
    }
    
    public void setIdDiagrama(int idDiagrama) {
        this.idDiagrama = idDiagrama;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public Set<Imagen> getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set<Imagen> imagens) {
        this.imagens = imagens;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


