package com.wad.model;
// Generated 12/06/2018 08:59:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private String nombre;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Grupo() {
    }

    public Grupo(String nombre, Set<Usuario> usuarios) {
       this.nombre = nombre;
       this.usuarios = usuarios;
    }
    public Grupo(int parseInt) {
        this.idGrupo = parseInt;
    }

    public Grupo(String nombre) {
        this.nombre = nombre;
    }
     
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


