package com.wad.model;
// Generated 12/06/2018 08:59:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int idTipo;
     private String nbTipo;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(int idTipo) {
        this.idTipo = idTipo;
    }
    public TipoUsuario(int idTipo, String nbTipo, Set<Usuario> usuarios) {
       this.idTipo = idTipo;
       this.nbTipo = nbTipo;
       this.usuarios = usuarios;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getNbTipo() {
        return this.nbTipo;
    }
    
    public void setNbTipo(String nbTipo) {
        this.nbTipo = nbTipo;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


