package com.project.model;
// Generated 21/05/2018 01:44:59 AM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {
    private Integer id;
    private String username;
    private  String mail;
    private  String password;

    public Usuarios() {
    }

    public Usuarios(String username, String mail, String password) {
       this.username = username;
       this.mail = mail;
       this.password = password;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}


